apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blockchain-engineering:tagname
  template:
    metadata:
      labels:
        app: blockchain-engineering:tagname
    spec:
      containers:
      - name: blockchain-engineering:tagname
        image: kheoss/blockchain-engineering:tagname
        ports:
        - containerPort: 8080

